import { render, screen, within } from "@testing-library/react";
import { describe, expect, it } from "vitest";

import Home from "@/app/page";
import RootLayout, { metadata } from "@/app/layout";

/**
 * Structural tests for the layout shell.
 *
 * SCOPE LIMIT: jsdom has no layout engine and does not apply Tailwind, so
 * nothing here proves anything about *visual* layout — column counts, sticky
 * behaviour, and overflow are all untestable at this level and are verified in
 * a browser instead. These tests cover the spec's DOM-level criteria only.
 */
describe("homepage structure", () => {
  it("uses one of each semantic landmark", () => {
    render(<Home />);

    expect(screen.getByRole("banner")).toBeInTheDocument(); // <header>
    expect(screen.getByRole("main")).toBeInTheDocument();
    expect(screen.getByRole("contentinfo")).toBeInTheDocument(); // <footer>
    expect(screen.getByRole("navigation", { name: "Main" })).toBeInTheDocument();
  });

  it("nests the nav inside the header", () => {
    render(<Home />);

    const header = screen.getByRole("banner");
    expect(within(header).getByRole("navigation")).toBeInTheDocument();
  });

  it("composes the regions in mockup order", () => {
    const { container } = render(<Home />);

    const topLevel = Array.from(container.children).map((el) =>
      el.tagName.toLowerCase(),
    );

    // navbar, hero, main (grid + chat), footer
    expect(topLevel).toEqual(["header", "section", "main", "footer"]);
  });

  it("puts the property grid before the chat panel in document order", () => {
    render(<Home />);

    const main = screen.getByRole("main");
    const grid = within(main).getByRole("region", { name: "Featured properties" });
    const chat = within(main).getByRole("region", { name: "AI agent chat" });

    // Node.DOCUMENT_POSITION_FOLLOWING — chat comes after grid, which is what
    // makes the single-column mobile stack order correct.
    expect(grid.compareDocumentPosition(chat) & 4).toBeTruthy();
  });
});

describe("root layout", () => {
  it("puts the serif font's CSS variable on <html> so font-serif resolves", async () => {
    // Rendered to a string rather than into jsdom: RootLayout returns <html>
    // and <body>, which cannot be mounted inside an existing document.
    const { renderToStaticMarkup } = await import("react-dom/server");
    const html = renderToStaticMarkup(
      <RootLayout>
        <p>content</p>
      </RootLayout>,
    );

    // The class name itself comes from the next/font stub — asserted only as
    // "something was applied", since the real value is build-generated.
    expect(html).toMatch(/<html[^>]*class="[^"]*mock-font-variable-Lora/);
  });
});

describe("metadata", () => {
  it("is project-specific, not the create-next-app default", () => {
    expect(metadata.title).toContain("Home Advisor");
    expect(metadata.title).not.toBe("Create Next App");
    expect(metadata.description).toBeTruthy();
    expect(metadata.description).not.toContain("Generated by create next app");
  });
});
